CREATE DATABASE TESTE;

USE TESTE;

CREATE TABLE PESSOA_FISICA (
	ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    CPF VARCHAR(14) NOT NULL,
    NOME VARCHAR(100) NOT NULL,
    DATA_NASCIMENTO VARCHAR(10) NOT NULL,
    ENDERECO VARCHAR(100) NOT NULL,
    TELEFONE VARCHAR(15) NOT NULL,
    CEP VARCHAR(10) NOT NULL
);

CREATE TABLE PESSOA_JURIDICA (
	ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    CNPJ VARCHAR(18) NOT NULL,
    NOME VARCHAR(100) NOT NULL,
    RAZAO_SOCIAL VARCHAR(100) NOT NULL,
    ENDERECO VARCHAR(100) NOT NULL,
    TELEFONE VARCHAR(15) NOT NULL,
    CEP VARCHAR(10) NOT NULL
);